# Site settings
title: Huzujun's Road
description: A blog about huzujun's study and life
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huzujun.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
google_verify: 2D5zbZ2Vatb8CeFj1cUCRdJZ3SQatSUlQesml02jEPo
# User settings
username: Hu Zujun
user_description: ACMer,Student in BJTU
user_title: Huzujun's Road
email: huzujun_001@163.com
twitter_username: huzujun
github_username:  huzujun
gplus_username:  huzujun
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Links
    url: /links

gitalk:
  enable: true
  githubID: huzujun 
  repo: huzujun.github.io
  ClientID: ae4f9c0162606fea64f4
  ClientSecret: 371313f179238c151029431a491797baabef99e5
  adminUser: huzujun
  distractionFreeMode: true

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# paginate
paginate: 10
paginate_path: "/page:num"
