# Site settings
title: KyleYoung
description: KyleYoung
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KyleYoung
user_description: KyleYoung
user_title: The only time an OIer can cry is when it's all over.
email: kyleyoung_ymj@163.com
twitter_username: kyleyoung_ymj
github_username:  kyleyoung-ymj
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: https://kyleyoung-ymj.github.io/
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
