# Site settings
title: KyleYoung
description: KyleYoung's blog
baseurl: "https://kyleyoung-ymj.github.io" # the subpath of your site, e.g. /blog
url: "https://kyleyoung-ymj.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KyleYoung
user_description: kyleyoung-ymj
user_title: ACs speak louder than words.
email: kyleyoung_ymj@163.com
twitter_username: kyleyoung_ymj
github_username:  kyleyoung-ymj
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about
  - title: Links
    url: /links

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# duoshuo
comments :
  provider : duoshuo
  duoshuo : 
  short_name : kyleyoung

# paginate
paginate: 10
paginate_path: "/page:num"
